function controller = designAttitudePID(axisInertia_kg_m2, ...
    naturalFrequency_rad_s, dampingRatio, integralPole_rad_s)
%DESIGNATTITUDEPID Calculate scalar attitude PID gains from response targets.

    validateattributes(axisInertia_kg_m2, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, ...
        'axisInertia_kg_m2');
    validateattributes(naturalFrequency_rad_s, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, ...
        'naturalFrequency_rad_s');
    validateattributes(dampingRatio, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, ...
        'dampingRatio');
    validateattributes(integralPole_rad_s, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'}, mfilename, ...
        'integralPole_rad_s');

    controller.Kp = axisInertia_kg_m2 * ...
        (naturalFrequency_rad_s^2 + 2 * dampingRatio * ...
         naturalFrequency_rad_s * integralPole_rad_s);
    controller.Ki = axisInertia_kg_m2 * integralPole_rad_s * ...
        naturalFrequency_rad_s^2;
    controller.Kd = axisInertia_kg_m2 * ...
        (2 * dampingRatio * naturalFrequency_rad_s + ...
         integralPole_rad_s);
end
