function quaternion = rotationToQuaternion(rotation)
%ROTATIONTOQUATERNION Return normalized [w; x; y; z] from a rotation matrix.

    validateattributes(rotation, {'numeric'}, ...
        {'size', [3, 3], 'real', 'finite'}, mfilename, 'rotation');
    traceValue = trace(rotation);
    if traceValue > 0
        scale = 2 * sqrt(1 + traceValue);
        quaternion = [0.25 * scale; ...
            (rotation(3, 2) - rotation(2, 3)) / scale; ...
            (rotation(1, 3) - rotation(3, 1)) / scale; ...
            (rotation(2, 1) - rotation(1, 2)) / scale];
    else
        [~, largestIndex] = max(diag(rotation));
        if largestIndex == 1
            scale = 2 * sqrt(max(0, 1 + rotation(1, 1) - ...
                rotation(2, 2) - rotation(3, 3)));
            quaternion = [(rotation(3, 2) - rotation(2, 3)) / scale; ...
                0.25 * scale; ...
                (rotation(1, 2) + rotation(2, 1)) / scale; ...
                (rotation(1, 3) + rotation(3, 1)) / scale];
        elseif largestIndex == 2
            scale = 2 * sqrt(max(0, 1 - rotation(1, 1) + ...
                rotation(2, 2) - rotation(3, 3)));
            quaternion = [(rotation(1, 3) - rotation(3, 1)) / scale; ...
                (rotation(1, 2) + rotation(2, 1)) / scale; ...
                0.25 * scale; ...
                (rotation(2, 3) + rotation(3, 2)) / scale];
        else
            scale = 2 * sqrt(max(0, 1 - rotation(1, 1) - ...
                rotation(2, 2) + rotation(3, 3)));
            quaternion = [(rotation(2, 1) - rotation(1, 2)) / scale; ...
                (rotation(1, 3) + rotation(3, 1)) / scale; ...
                (rotation(2, 3) + rotation(3, 2)) / scale; ...
                0.25 * scale];
        end
    end
    quaternion = quaternion / norm(quaternion);
    if quaternion(1) < 0
        quaternion = -quaternion;
    end
end
