function animateDrone6DOF(config, simulation, playbackSpeed)
%ANIMATEDRONE6DOF Animate the full quaternion attitude and 3D translation.

    if nargin < 3
        playbackSpeed = 1;
    end
    validateattributes(playbackSpeed, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, 'playbackSpeed');

    time = simulation.time_s;
    position = simulation.position_m;
    motorThrust = simulation.motorThrust_N;
    motorLeverArms = config.motorLeverArms;
    numberOfMotors = config.numberOfMotors;
    typicalTimeStep = median(diff(time));
    targetFrameRate = 30;
    samplesPerFrame = max(1, round(1 / ...
        (targetFrameRate * typicalTimeStep)));
    frameIndices = unique([1:samplesPerFrame:numel(time), numel(time)]);

    armLength = max(vecnorm(motorLeverArms, 2, 2));
    cameraHalfWidth = max(0.40, 3 * armLength);
    trailDuration_s = 2;
    if any(simulation.rateModeActive)
        activeIndices = find(simulation.rateModeActive);
        trailDuration_s = max(trailDuration_s, ...
            time(activeIndices(end)) - time(activeIndices(1)) + 0.5);
    end
    bodyAxisLength = max(0.12, armLength);
    thrustArrowScale_m_per_N = max(0.004, armLength / ...
        (2 * max(config.maxThrust)));

    figureHandle = figure('Color', 'w', ...
        'Name', 'Full 6DOF drone animation');
    axesHandle = axes(figureHandle);
    hold(axesHandle, 'on');
    grid(axesHandle, 'on');
    axis(axesHandle, 'equal');
    view(axesHandle, 38, 24);
    xlabel(axesHandle, 'world x: left (m)');
    ylabel(axesHandle, 'world y: backward (m)');
    zlabel(axesHandle, 'world z: up (m)');

    centerHandle = scatter3(axesHandle, 0, 0, 0, 90, 'k', 'filled');
    motorHandle = scatter3(axesHandle, zeros(numberOfMotors, 1), ...
        zeros(numberOfMotors, 1), zeros(numberOfMotors, 1), 150, ...
        'filled', 'MarkerFaceColor', [0.12, 0.47, 0.71], ...
        'MarkerEdgeColor', [0.1, 0.1, 0.1]);
    armHandles = gobjects(numberOfMotors, 1);
    labelHandles = gobjects(numberOfMotors, 1);
    for motorIndex = 1:numberOfMotors
        armHandles(motorIndex) = plot3(axesHandle, [0, 0], [0, 0], ...
            [0, 0], '-', 'Color', [0.25, 0.25, 0.25], 'LineWidth', 3);
        labelHandles(motorIndex) = text(axesHandle, 0, 0, 0, ...
            sprintf('%s %s', config.motorNames{motorIndex}, ...
            config.motorSpinDirection{motorIndex}), 'FontWeight', 'bold');
    end

    thrustHandle = quiver3(axesHandle, zeros(numberOfMotors, 1), ...
        zeros(numberOfMotors, 1), zeros(numberOfMotors, 1), ...
        zeros(numberOfMotors, 1), zeros(numberOfMotors, 1), ...
        zeros(numberOfMotors, 1), 0, 'Color', [0.85, 0.2, 0.15], ...
        'LineWidth', 1.6, 'MaxHeadSize', 0.7);
    xAxisHandle = makeAxisArrow(axesHandle, [0.85, 0.15, 0.15]);
    yAxisHandle = makeAxisArrow(axesHandle, [0.15, 0.65, 0.2]);
    zAxisHandle = makeAxisArrow(axesHandle, [0.15, 0.3, 0.9]);
    trailHandle = plot3(axesHandle, 0, 0, 0, '-', ...
        'Color', [0.35, 0.35, 0.35], 'LineWidth', 1.3);
    commandAltitudeHandle = plot3(axesHandle, [-0.1, 0.1], ...
        [0, 0], [0, 0], '--', 'Color', [0.5, 0.2, 0.7], ...
        'LineWidth', 1.2);

    % Keep the main view close enough to see the motors. A small inset shows
    % the complete trajectory so large maneuvers still have spatial context.
    overviewAxes = axes(figureHandle, ...
        'Position', [0.70, 0.66, 0.27, 0.27]);
    plot3(overviewAxes, position(:, 1), position(:, 2), position(:, 3), ...
        '-', 'Color', [0.75, 0.75, 0.75], 'LineWidth', 1.0);
    hold(overviewAxes, 'on');
    overviewProgressHandle = plot3(overviewAxes, position(1, 1), ...
        position(1, 2), position(1, 3), '-', ...
        'Color', [0.10, 0.40, 0.80], 'LineWidth', 1.5);
    overviewMarkerHandle = scatter3(overviewAxes, position(1, 1), ...
        position(1, 2), position(1, 3), 28, 'k', 'filled');
    grid(overviewAxes, 'on');
    axis(overviewAxes, 'equal');
    view(overviewAxes, 38, 24);
    title(overviewAxes, 'Full path');
    overviewAxes.FontSize = 8;

    for frameNumber = 1:numel(frameIndices)
        if ~isvalid(figureHandle)
            return;
        end
        sampleIndex = frameIndices(frameNumber);
        center = position(sampleIndex, :).';
        rotationNow = simulation.rotationBodyToWorld(:, :, sampleIndex);
        motorWorld = center + rotationNow * motorLeverArms.';
        thrustDirection = rotationNow * [0; 0; 1];
        thrustVectors = thrustDirection * ...
            (motorThrust(sampleIndex, :) * thrustArrowScale_m_per_N);

        set(centerHandle, 'XData', center(1), 'YData', center(2), ...
            'ZData', center(3));
        set(motorHandle, 'XData', motorWorld(1, :), ...
            'YData', motorWorld(2, :), 'ZData', motorWorld(3, :));
        for motorIndex = 1:numberOfMotors
            set(armHandles(motorIndex), ...
                'XData', [center(1), motorWorld(1, motorIndex)], ...
                'YData', [center(2), motorWorld(2, motorIndex)], ...
                'ZData', [center(3), motorWorld(3, motorIndex)]);
            set(labelHandles(motorIndex), 'Position', ...
                motorWorld(:, motorIndex).' + [0.015, 0.015, 0.015]);
        end
        set(thrustHandle, 'XData', motorWorld(1, :), ...
            'YData', motorWorld(2, :), 'ZData', motorWorld(3, :), ...
            'UData', thrustVectors(1, :), ...
            'VData', thrustVectors(2, :), ...
            'WData', thrustVectors(3, :));

        bodyAxes = rotationNow * (bodyAxisLength * eye(3));
        updateAxisArrow(xAxisHandle, center, bodyAxes(:, 1));
        updateAxisArrow(yAxisHandle, center, bodyAxes(:, 2));
        updateAxisArrow(zAxisHandle, center, bodyAxes(:, 3));

        trailStart = max(1, sampleIndex - ...
            round(trailDuration_s / typicalTimeStep));
        set(trailHandle, ...
            'XData', position(trailStart:sampleIndex, 1), ...
            'YData', position(trailStart:sampleIndex, 2), ...
            'ZData', position(trailStart:sampleIndex, 3));
        set(overviewProgressHandle, ...
            'XData', position(1:sampleIndex, 1), ...
            'YData', position(1:sampleIndex, 2), ...
            'ZData', position(1:sampleIndex, 3));
        set(overviewMarkerHandle, 'XData', center(1), ...
            'YData', center(2), 'ZData', center(3));
        altitudeCommand = simulation.altitudeCommand_m(sampleIndex);
        set(commandAltitudeHandle, ...
            'XData', center(1) + [-0.12, 0.12], ...
            'YData', center(2) + [0, 0], ...
            'ZData', [altitudeCommand, altitudeCommand]);

        xlim(axesHandle, center(1) + [-cameraHalfWidth, cameraHalfWidth]);
        ylim(axesHandle, center(2) + [-cameraHalfWidth, cameraHalfWidth]);
        zlim(axesHandle, center(3) + [-cameraHalfWidth, cameraHalfWidth]);
        command = simulation.commandAngles_deg(sampleIndex, :);
        actual = simulation.actualAngles_deg(sampleIndex, :);
        if simulation.rateModeActive(sampleIndex)
            rateCommand = ...
                simulation.rateCommandFlight_deg_s(sampleIndex, :);
            flipProgress = ...
                simulation.rateModeCumulativeActualRotation_deg( ...
                sampleIndex, :);
            title(axesHandle, sprintf([ ...
                't %.2f s | RATE cmd R/P/Y %.0f/%.0f/%.0f deg/s | ' ...
                'progress %.0f/%.0f/%.0f deg'], ...
                time(sampleIndex), rateCommand, flipProgress));
        else
            actual = atan2(sin(actual * pi / 180), ...
                cos(actual * pi / 180)) * 180 / pi;
            title(axesHandle, sprintf([ ...
                't %.2f s | ATT cmd R/P/Y %.1f/%.1f/%.1f deg | ' ...
                'actual %.1f/%.1f/%.1f deg'], ...
                time(sampleIndex), command, actual));
        end

        drawnow;
        if frameNumber < numel(frameIndices)
            frameTime = time(frameIndices(frameNumber + 1)) - ...
                time(sampleIndex);
            pause(max(0, frameTime / playbackSpeed));
        end
    end
end

function arrowHandle = makeAxisArrow(axesHandle, color)
    arrowHandle = quiver3(axesHandle, 0, 0, 0, 0, 0, 0, 0, ...
        'Color', color, 'LineWidth', 2);
end

function updateAxisArrow(arrowHandle, origin, vector)
    set(arrowHandle, 'XData', origin(1), 'YData', origin(2), ...
        'ZData', origin(3), 'UData', vector(1), ...
        'VData', vector(2), 'WData', vector(3));
end
