function plotDirectionalAuthority(authority)
%PLOTDIRECTIONALAUTHORITY Plot moment and angular-acceleration envelopes.

    closedAngles = [authority.directionAngles_rad; ...
                    authority.directionAngles_rad(1) + 2 * pi];
    closedMoment = [authority.momentLimit_Nm; authority.momentLimit_Nm(1)];
    closedAcceleration = [authority.angularAccelerationLimit_rad_s2; ...
                          authority.angularAccelerationLimit_rad_s2(1)];

    figureHandle = figure('Color', 'w', ...
        'Name', 'Directional control authority');

    momentAxes = polaraxes('Parent', figureHandle, ...
        'Position', [0.05, 0.16, 0.41, 0.72]);
    hold(momentAxes, 'on');
    polarplot(momentAxes, closedAngles, closedMoment, ...
        'LineWidth', 2, 'Color', [0.12, 0.47, 0.71]);
    polarplot(momentAxes, closedAngles, ...
        authority.minimumMoment_Nm * ones(size(closedAngles)), '--', ...
        'LineWidth', 1.1, 'Color', [0.35, 0.35, 0.35]);
    markExtrema(momentAxes, authority.directionAngles_rad, ...
        authority.momentLimit_Nm);
    title(momentAxes, 'Constant-altitude moment authority');
    momentAxes.ThetaZeroLocation = 'right';
    momentAxes.ThetaDir = 'counterclockwise';
    momentAxes.RAxis.Label.String = 'Moment (N m)';

    accelerationAxes = polaraxes('Parent', figureHandle, ...
        'Position', [0.54, 0.16, 0.41, 0.72]);
    hold(accelerationAxes, 'on');
    polarplot(accelerationAxes, closedAngles, closedAcceleration, ...
        'LineWidth', 2, 'Color', [0.85, 0.33, 0.10]);
    polarplot(accelerationAxes, closedAngles, ...
        authority.minimumAngularAcceleration_rad_s2 * ...
        ones(size(closedAngles)), '--', 'LineWidth', 1.1, ...
        'Color', [0.35, 0.35, 0.35]);
    markExtrema(accelerationAxes, authority.directionAngles_rad, ...
        authority.angularAccelerationLimit_rad_s2);
    title(accelerationAxes, 'Angular-acceleration authority');
    accelerationAxes.ThetaZeroLocation = 'right';
    accelerationAxes.ThetaDir = 'counterclockwise';
    accelerationAxes.RAxis.Label.String = 'Angular acceleration (rad/s^2)';

    annotation(figureHandle, 'textbox', [0.12, 0.01, 0.76, 0.09], ...
        'String', sprintf([ ...
        '0 deg = +Mx, 90 deg = +My   |   ' ...
        'moment anisotropy %.3f   |   acceleration anisotropy %.3f'], ...
        authority.momentAnisotropy, ...
        authority.angularAccelerationAnisotropy), ...
        'HorizontalAlignment', 'center', 'EdgeColor', 'none', ...
        'FontWeight', 'bold');
end

function markExtrema(axesHandle, angles, radii)
    [~, minimumIndex] = min(radii);
    [~, maximumIndex] = max(radii);
    polarplot(axesHandle, angles(minimumIndex), radii(minimumIndex), 'o', ...
        'MarkerSize', 7, 'MarkerFaceColor', [0.80, 0.15, 0.15], ...
        'MarkerEdgeColor', 'none');
    polarplot(axesHandle, angles(maximumIndex), radii(maximumIndex), 'o', ...
        'MarkerSize', 7, 'MarkerFaceColor', [0.15, 0.65, 0.25], ...
        'MarkerEdgeColor', 'none');
end
